# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    name: n8n-service
    runtime: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: danbraindb
      - key: DB_POSTGRESDB_HOST
        value: dpg-cvkts4idbo4c73fbcgvg-a
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_USER
        value: danbraindb_user
      - key: DB_POSTGRESDB_PASSWORD
        sync: false  # set manually in Render after deploy
      - key: DB_POSTGRESDB_SSL
        value: true

      # Add login protection
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: Dani.boy
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false  # set manually

      # Encryption key for credential security
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # External webhook + editor URLs
      - key: WEBHOOK_URL
        value: https://dan-assistant.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://dan-assistant.onrender.com

      # Optional (Recommended by n8n)
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS
        value: true

